# Generated by Django 4.2.2 on 2023-07-19 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ('-nombre',)},
        ),
    ]
